#!/usr/bin/env bash
# to ping the ip passed as an arg 5 times
if [ $# -eq 0 ]; then
	echo 'Usage: 5-is_the_host_on_the_network {IP_ADDRESS}'
else
	for i in {1..5}; do
		ping -c 1 $IP > /dev/null
	done
fi
