#!/usr/bin/env bash
#  displays the PID, along with the process name, of processes whose name contain the word:

for pid in /proc/*/comm; do
	if grep -q "^bash$" "$pid"; then
		process_pid=$(awk -F/ '{print $(NF-1)}' "$pid")
		process_name=$(cat "$pid")
		echo "$process_pid $process_name"
	fi
done
